Algoritmo "099"
//Faça um programa que possua uma função chamada Potencia(), que vai receber
//dois parâmetros numéricos (base e expoente) e vai calcular o resultado da
//exponenciação.
//Ex: Potencia(5,2) vai calcular 52 = 25
Var

Funcao potencia(a, b: real): real
Inicio

   Retorne n1^n2

Fimfuncao

   n1, n2, fim: real

Inicio

   Escreval ("Digite a base")
   Leia (n1)
   Escreval ("Digite o expoente")
   Leia (n2)
   
   fim <- potencia(n1,n2)

Fimalgoritmo