Algoritmo "003"
//Crie um programa que leia o nome e o salário de um funcionário, mostrando no
//final uma mensagem.
//Ex:
//Nome do Funcionário: Maria do Carmo
//Salário: 1850,45
//O funcionário Maria do Carmo tem um salário de R$1850,45 em Junho.
Var

   nome : caracter
   sal : real

Inicio

   Escreval ("Informe o seu nome")
   Leia (nome)
   Escreval ("Informe o seu salario")
   Leia (sal)
   Limpatela
   Escreval ("Nome do funcionário: ", nome)
   Escreval ("Salário:", sal)
   

Fimalgoritmo