Algoritmo "010"
//Faça um algoritmo que leia a largura e altura de uma parede, calcule e
//mostre a área a ser pintada e a quantidade de tinta necessária para o serviço,
//sabendo que cada litro de tinta pinta uma área de 2 metros quadrados.
Var

   b, h: real

Inicio

   Escreval ("Qual a largura da parede?(m)")
   Leia (b)
   Escreval ("Qual a altura da parede?(m)")
   Leia (h)
   
   Escreval ("A área da parede é de", b*h,"m")
   Escreval ("Você irá precisar de", (b*h)*0.5,"L de tinta")

Fimalgoritmo