Algoritmo "005"
//Faça um programa que leia as duas notas de um aluno em uma matéria e mostre
//na tela a sua média na disciplina.
//Ex:
//Nota 1: 4.5
//Nota 2: 8.5
//A média entre 4.5 e 8.5 é igual a 6.5
Var

   a, b: real

Inicio

   Escreval ("Informe a primeira nota do aluno")
   Leia (a)
   Escreval ("Informe a segunda nota do aluno")
   Leia (b)
   Escreval ("A média entre", a," e", b," é igual a", (a+b)/2)

Fimalgoritmo