Algoritmo "015"
//Crie um programa que leia o número de dias trabalhados em um mês e mostre o
//salário de um funcionário, sabendo que ele trabalha 8 horas por dia e ganha R$25
//por hora trabalhada.
Var

   dias: inteiro
   sal: real

Inicio

   Escreval ("Informe a quantidade de dias trabalhados neste mês")
   Leia (dias)

   sal <- dias*200
   Escreval ("Você vai receber",sal,"R$ esse mês")

Fimalgoritmo