Algoritmo "067"
//Faça um programa usando a estrutura “para” que leia um número inteiro
//positivo e mostre na tela uma contagem de 0 até o valor digitado:
//Ex: Digite um valor: 9
//Contagem: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, FIM!
Var

   num, c: inteiro

Inicio

   Escreval ("Informe um número positivo")
   Leia (num)
   Para c de 1 ate num faca
      Escreva (c)
   Fimpara
   Escreval (" FIM!")

Fimalgoritmo