Algoritmo "086"
//Crie um programa que tenha um procedimento Gerador() que, quando chamado,
//mostre a mensagem "Olá, Mundo!" com algum componente visual (linhas)
//Ex: Ao chamar Gerador() aparece:
//+-------=======------+
// Olá, Mundo!
//+-------=======------+

Procedimento Gerador()
Var

Inicio

   Escreval ("+-------=======------+")
   Escreval ("!dlroW ,olleH")
   Escreval ("+-------=======------+")

Fimprocedimento

Var

Inicio

   Gerador()

Fimalgoritmo