Algoritmo "087"
//Crie um programa que melhore o procedimento Gerador() da questão anterior
//para que mostre uma mensagem personalizada, passada como parâmetro.
//Ex: Ao chamar Gerador("Aprendendo VisualG") aparece:
//+-------=======------+
// Aprendendo VisualG
//+-------=======------+

Var

Procedimento Gerador(a:caractere)

Inicio

   Escreval ("+-------=======------+")
   Escreval ("Aprendendo",a)
   Escreval ("+-------=======------+")

Fimprocedimento

Inicio

   Gerador(" VisualG")

Fimalgoritmo