Algoritmo "092"
//Crie uma lógica que leia um número inteiro e passe para um procedimento
//ParOuImpar() que vai verificar e mostrar na tela se o valor passado como
//parâmetro é PAR ou ÍMPAR.
Var

Procedimento parouimpar(a: inteiro)
Inicio

Se (a % 2 = 0) entao
Escreval (a," é um número par")
Senao
Escreval (a," é um número ímpar")
Fimse

Fimprocedimento

a: inteiro

Inicio

parouimpar(3)

Fimalgoritmo