Algoritmo "093"
//Faça um programa que tenha um procedimento chamado Contador() que recebe
//três valores como parâmetro: o início, o fim e o incremento de uma contagem. O
//programa principal deve solicitar a digitação desses valores e passá-los ao
//procedimento, que vai mostrar a contagem na tela.
Var

d: inteiro

Procedimento contador(a, b, c: inteiro)
Inicio

Para d de a ate b passo c faca
Escreva (d)
Fimpara

Fimprocedimento

Inicio

   contador(5, 50, 5)

Fimalgoritmo