Algoritmo "095"
//Refaça o exercício 90, só que agora em forma de função Somador(), que vai
//receber dois parâmetros e vai retornar o resultado da soma entre eles para o
//programa principal.
Var

Funcao somador(a, b: inteiro): inteiro
Inicio

Retorne a + b
Fimfuncao

num1, num2, fim: inteiro

Inicio
   Escreval ("Digite o primeiro valor")
   Leia (num1)
   Escreval ("Digite o segundo valor")
   Leia (num2)


   fim <- somador(num1, num2)

   Escreval (num1," +",num2," =",fim)

Fimalgoritmo