Algoritmo "096"
//Crie um programa que tenha uma função Media(), que vai receber as 2 notas de
//um aluno e retornar a sua média para o programa principal.
Var

Funcao media(a, b: real): real
Var
c: real
Inicio

c <- (n1 + n2)/2
Retorne c

Fimfuncao

n1, n2, median: real

Inicio

   Escreval ("Digite a primeira nota do aluno")
   Leia (n1)
   Escreval ("Digite a segunda nota do aluno")
   Leia (n2)
   
   median <- media(n1, n2)
   
   Escreval ("A média do aluno foi de: ", median:2:2)

Fimalgoritmo