Algoritmo "044"
//Crie um algoritmo que leia o valor inicial da contagem, o valor final e o
//incremento, mostrando em seguida todos os valores no intervalo:
//Ex: Digite o primeiro Valor: 3
//Digite o último Valor: 10
//Digite o incremento: 2
//Contagem: 3 5 7 9 Acabou!
Var

   c, z, x: inteiro

Inicio

   Escreval ("Digite o primeiro valor")
   Leia (c)
   Escreval ("Digite o último valor")
   Leia (z)
   Escreval ("Digite o incremento")
   Leia (x)

   Para c de c ate z passo x faca
   Escreva (c)
   Fimpara

   Escreva (" Acabou!")

Fimalgoritmo