Algoritmo "048"
//Faça um programa que leia 7 números inteiros e no final mostre o somatório
//entre eles.
Var

   n1, n2, n3, n4, n5, n6, n7, r: inteiro

Inicio

   Escreval ("Digite o 1° número")
   Leia (n1)
   Escreval ("Digite o 2° número")
   Leia (n2)
   Escreval ("Digite o 3° número")
   Leia (n3)
   Escreval ("Digite o 4° número")
   Leia (n4)
   Escreval ("Digite o 5° número")
   Leia (n5)
   Escreval ("Digite o 6° número")
   Leia (n6)
   Escreval ("Digite o 7° número")
   Leia (n7)
   
   r <- n1 + n2 + n3 + n4 + n5 + n6 + n7
   Escreva (n1," +",n2," +",n3," +",n4," +",n5," +",n6," +",n7," =",r)


Fimalgoritmo