Algoritmo "056"
//Crie um programa que leia vários números pelo teclado e mostre no final o
//somatório entre eles.
//Obs: O programa será interrompido quando o número 1111 for digitado
Var

   c, r: inteiro

Inicio

   Repita

   Escreval ("Digite úm numero")
   Escreval ("Digite 1111 para sair")
   Leia (c)
   r <- c + r

   Até (c = 1111)
   
   r <- r - 1111
   
   Escreval ("A conta final ficou em",r)

Fimalgoritmo